export interface Strike {
  callAskIv: number
  callAskPrice: number
  callAskSize: number
  callBidIv: number
  callBidPrice: number
  callBidSize: number
  callMidIv: number
  callOpenInterest: number
  callSmvVol: number
  callValue: number
  callVolume: number
  delta: number
  driftlessTheta: number
  dte: 5
  expirDate: string
  extCallValue: number
  extPutValue: number
  extSmvVol: number
  gamma: number
  phi: number
  putAskIv: number
  putAskPrice: number
  putAskSize: number
  putBidIv: number
  putBidPrice: number
  putBidSize: number
  putMidIv: number
  putOpenInterest: number
  putSmvVol: number
  putValue: number
  putVolume: number
  quoteDate: string
  residualRate: number
  rho: number
  smvVol: number
  snapShotDate: string
  snapShotEstTime: string
  spotPrice: number
  stockPrice: number
  strike: number
  theta: number
  ticker: string
  tradeDate: string
  updatedAt: string
  vega: number
}
